function [B, S_lbar, S_hbar]= constraint3sd(e,m,E_req,E_bat,eta_ch,del_t)

% Input Matrix
if(m==1)
    B1=[zeros(1,20) ones(1,1) zeros(1,3);...
        zeros(1,20) ones(1,2) zeros(1,2);...
        zeros(1,20) ones(1,3) zeros(1,1);...
        zeros(1,20) ones(1,4);...
        ones(1,1)  zeros(1,19) ones(1,4);...
        ones(1,2) zeros(1,18)  ones(1,4);...
        ones(1,3) zeros(1,17) ones(1,4);...
        ones(1,4) zeros(1,16) ones(1,4)];
    for i=1:8:320
        B([i:i+7],:)=B1;
    end
    % Bounds on energy state
    j2=1;
    for i=1:8:320
        S_lbar(i)=(1/eta_ch*del_t)*(E_req(j2,e)-E_bat);
        S_lbar(i+1)=(1/eta_ch*del_t)*(E_req(j2,e)-E_bat);
        S_lbar(i+2)=(1/eta_ch*del_t)*(E_req(j2,e)-E_bat);
        S_lbar(i+3)=(1/eta_ch*del_t)*(E_req(j2,e)-E_bat);
        S_lbar(i+4)=(1/eta_ch*del_t)*(E_req(j2,e)-E_bat);
        S_lbar(i+5)=(1/eta_ch*del_t)*(E_req(j2,e)-E_bat);
        S_lbar(i+6)=(1/eta_ch*del_t)*(E_req(j2,e)-E_bat);
        S_lbar(i+7)=(1/eta_ch*del_t)*(E_req(j2,e)-E_bat);
        
        S_hbar(i)=(1/eta_ch*del_t)*E_req(j2,e);
        S_hbar(i+1)=(1/eta_ch*del_t)*E_req(j2,e);
        S_hbar(i+2)=(1/eta_ch*del_t)*E_req(j2,e);
        S_hbar(i+3)=(1/eta_ch*del_t)*E_req(j2,e);
        S_hbar(i+4)=(1/eta_ch*del_t)*E_req(j2,e);
        S_hbar(i+5)=(1/eta_ch*del_t)*E_req(j2,e);
        S_hbar(i+6)=(1/eta_ch*del_t)*E_req(j2,e);
        S_hbar(i+7)=(1/eta_ch*del_t)*E_req(j2,e);
        j2=j2+1;
    end
    S_lbar=reshape(S_lbar,320,1);
    S_hbar=reshape(S_hbar,320,1);
else
    if(m==2)
        B1=[zeros(1,18) ones(1,1) zeros(1,5);...
            zeros(1,18) ones(1,2) zeros(1,4);...
            zeros(1,18) ones(1,3) zeros(1,3);...
            zeros(1,18) ones(1,4) zeros(1,2);...
            zeros(1,18) ones(1,5) zeros(1,1);...
            zeros(1,18) ones(1,6);...
            ones(1,1) zeros(1,17) ones(1,6);...
            ones(1,2) zeros(1,16) ones(1,6)];
        B2=[zeros(1,22) ones(1,1) zeros(1,1);...
            zeros(1,22) ones(1,2);...
            ones(1,1) zeros(1,21) ones(1,2);...
            ones(1,2) zeros(1,20) ones(1,2);...
            ones(1,3) zeros(1,19) ones(1,2);...
            ones(1,4) zeros(1,18) ones(1,2);...
            ones(1,5) zeros(1,17) ones(1,2);...
            ones(1,6) zeros(1,16) ones(1,2)];
        B3=[zeros(1,20) ones(1,1) zeros(1,3);...
            zeros(1,20) ones(1,2) zeros(1,2);...
            zeros(1,20) ones(1,3) zeros(1,1);...
            zeros(1,20) ones(1,4);...
            ones(1,1) zeros(1,19) ones(1,4);...
            ones(1,2) zeros(1,18) ones(1,4);...
            ones(1,3) zeros(1,17) ones(1,4);...
            ones(1,4) zeros(1,16) ones(1,4)];
            
        B4=[zeros(1,16) ones(1,1) zeros(1,7);...
            zeros(1,16) ones(1,2) zeros(1,6);...
            zeros(1,16) ones(1,3) zeros(1,5);...
            zeros(1,16) ones(1,4) zeros(1,4);...
            zeros(1,16) ones(1,5) zeros(1,3);...
            zeros(1,16) ones(1,6) zeros(1,2);...
            zeros(1,16) ones(1,7) zeros(1,1);...
            zeros(1,16) ones(1,8)];
            
        Bbar=[B1;B2;B3;B4];
        t3=1;
        for i=1:8:320
            if(t3==33)
                t3=1;
            end
            B([i:i+7],:)=Bbar([t3:t3+7],:);
            t3=t3+8;
        end
        % Bounds on energy state
    j2=1;
    for i=1:8:320
        S_lbar(i)=(1/eta_ch*del_t)*(E_req(j2,e)-E_bat);
        S_lbar(i+1)=(1/eta_ch*del_t)*(E_req(j2,e)-E_bat);
        S_lbar(i+2)=(1/eta_ch*del_t)*(E_req(j2,e)-E_bat);
        S_lbar(i+3)=(1/eta_ch*del_t)*(E_req(j2,e)-E_bat);
        S_lbar(i+4)=(1/eta_ch*del_t)*(E_req(j2,e)-E_bat);
        S_lbar(i+5)=(1/eta_ch*del_t)*(E_req(j2,e)-E_bat);
        S_lbar(i+6)=(1/eta_ch*del_t)*(E_req(j2,e)-E_bat);
        S_lbar(i+7)=(1/eta_ch*del_t)*(E_req(j2,e)-E_bat);
        
        
        S_hbar(i)=(1/eta_ch*del_t)*E_req(j2,e);
        S_hbar(i+1)=(1/eta_ch*del_t)*E_req(j2,e);
        S_hbar(i+2)=(1/eta_ch*del_t)*E_req(j2,e);
        S_hbar(i+3)=(1/eta_ch*del_t)*E_req(j2,e);
        S_hbar(i+4)=(1/eta_ch*del_t)*E_req(j2,e);
        S_hbar(i+5)=(1/eta_ch*del_t)*E_req(j2,e);
        S_hbar(i+6)=(1/eta_ch*del_t)*E_req(j2,e);
        S_hbar(i+7)=(1/eta_ch*del_t)*E_req(j2,e);
        j2=j2+1;
    end
    S_lbar=reshape(S_lbar,320,1);
    S_hbar=reshape(S_hbar,320,1);
    end
end

    
end